<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />

<meta name="Generator" content="Pages 2.0.2" />
<title></title>
<link rel="stylesheet" type="text/css" media="screen" href="css/license.css" />
</head>
<body style="margin: 72pt 90pt 72pt 90pt; ">
<div><div class="layout_style_1"><div class="paragraph Heading_2" style="line-height: 15pt; margin-bottom: 0pt; margin-left: 0pt; margin-right: 0pt; margin-top: 0pt; padding-top: 0pt; text-indent: 0pt; color: #000000; line-height: 15pt; opacity: 1.00;">SOFTWARE LICENSE AGREEMENT</div>
<div class="paragraph Default" style="line-height: 15pt; margin-bottom: 0pt; margin-top: 0pt; color: #000000; font-weight: bold; line-height: 15pt; opacity: 1.00;  text-decoration: none;"> </div>
<div class="paragraph Text_body" style="line-height: 13pt; ">Pika Software has developed and licenses to users its software program marketed under the name Pika CMS (the "Software").  In consideration of the mutual promises set forth herein, the parties agree as follows:</div>
<div class="paragraph Heading_2" style="line-height: 15pt; text-decoration: none;"> </div>
<div class="paragraph Heading_1" style="line-height: 15pt; color: #000000; font-weight: bold; line-height: 15pt; opacity: 1.00;">1.  License</div>
<div class="paragraph Text_body_indent" style="line-height: 13pt; text-decoration: none;"> </div>
<div class="paragraph Text_body_indent" style="line-height: 13pt; ">Pika Software hereby grants to Client a perpetual, non-exclusive, limited license to use the Software in the United States of America as set forth in this Agreement.</div>
<div class="paragraph Default" style="line-height: 15pt; color: #000000; font-weight: bold; line-height: 15pt; opacity: 1.00;  text-decoration: none;"> </div>
<div class="paragraph Heading_1" style="line-height: 15pt; ">2.  License Restrictions</div>
<div class="paragraph Default" style="line-height: 15pt; margin-bottom: 0pt; margin-top: 0pt; color: #000000; font-weight: bold; line-height: 15pt; opacity: 1.00;  text-decoration: none;"> </div>
<div class="paragraph Text_body_indent" style="line-height: 13pt; ">Client shall not redistribute, license or sublicense the Pika CMS software, or transfer or convey the software or any right in the software to anyone else without the prior written consent of Pika Software.</div>
<div class="paragraph Heading_1" style="line-height: 15pt; color: #000000; line-height: 15pt; opacity: 1.00;  text-decoration: none;"> </div>
<div class="paragraph Heading_1" style="line-height: 15pt; ">3.  Contract Services</div>
<div class="paragraph Text_body_indent" style="line-height: 13pt; text-decoration: none;"> </div>
<div class="paragraph Default" style="line-height: 13pt; margin-bottom: 0pt; margin-top: 0pt; color: #000000; font-size: 11pt; line-height: 13pt; opacity: 1.00;">Pika Software will provide:</div>
<div class="paragraph Default" style="line-height: 13pt; margin-bottom: 0pt; margin-left: 0pt; margin-right: 0pt; margin-top: 0pt; padding-bottom: 0pt; padding-top: 0pt; text-align: left; text-indent: 0pt; color: #000000; font-family: 'TimesNewRomanPSMT', 'Times New Roman', 'serif'; font-size: 11pt; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: 0; line-height: 13pt; opacity: 1.00; text-decoration: none; text-transform: none;  text-decoration: none;"> </div>
<ol><li style="line-height: 15pt; margin-left: 18pt; padding-left: 18pt; text-indent: -18pt; "><div class="paragraph Default" style="line-height: 15pt; margin-bottom: 0pt; margin-left: 0pt; margin-right: 0pt; margin-top: 0pt; padding-bottom: 0pt; padding-top: 0pt; text-align: left; text-indent: -18pt; "><span style="color: #000000; font-family: 'Symbol'; font-size: 11pt; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: 0; opacity: 1.00; text-decoration: none; text-transform: none; " class="Bullet">•</span><span style="width: 11.8pt; " class="Spacer"></span><span style="color: #000000; font-family: 'TimesNewRomanPSMT', 'Times New Roman', 'serif'; font-size: 11pt; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: 0; line-height: 13pt; opacity: 1.00; text-decoration: none; text-transform: none; ">Technical support for administrators provided by phone and direct email.</span></div>
</li>
<li style="line-height: 15pt; margin-left: 18pt; padding-left: 18pt; text-indent: -18pt; "><div class="paragraph Default" style="line-height: 15pt; margin-bottom: 0pt; margin-left: 0pt; margin-right: 0pt; margin-top: 0pt; padding-bottom: 0pt; padding-top: 0pt; text-align: left; text-indent: -18pt; "><span style="color: #000000; font-family: 'Symbol'; font-size: 11pt; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: 0; opacity: 1.00; text-decoration: none; text-transform: none; " class="Bullet">•</span><span style="width: 11.8pt; " class="Spacer"></span><span style="color: #000000; font-family: 'TimesNewRomanPSMT', 'Times New Roman', 'serif'; font-size: 11pt; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: 0; line-height: 13pt; opacity: 1.00; text-decoration: none; text-transform: none; ">Online system documentation.</span></div>
</li>
<li style="line-height: 13pt; margin-left: 18pt; padding-left: 18pt; text-indent: -18pt; "><div class="paragraph WW_Body_Text_Indent_2" style="line-height: 13pt; margin-bottom: 0pt; margin-left: 0pt; margin-right: 0pt; margin-top: 0pt; padding-bottom: 0pt; padding-top: 0pt; text-align: left; text-indent: -18pt; "><span style="color: #000000; font-family: 'Symbol'; font-size: 11pt; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: 0; opacity: 1.00; text-decoration: none; text-transform: none; " class="Bullet">•</span><span style="width: 11.8pt; " class="Spacer"></span><span style="color: #000000; font-family: 'TimesNewRomanPSMT', 'Times New Roman', 'serif'; font-size: 11pt; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: 0; line-height: 13pt; opacity: 1.00; text-decoration: none; text-transform: none; ">Licenses for new software versions developed for one year inclusive of the Contract Date.</span></div>
</li>
</ol>
<div class="paragraph WW_Body_Text_Indent_2" style="line-height: 13pt; margin-bottom: 0pt; margin-left: 0pt; margin-top: 0pt; text-indent: 0pt; color: #000000; line-height: 13pt; opacity: 1.00;  text-decoration: none;"> </div>
<div class="paragraph Heading_1" style="line-height: 15pt; color: #000000; line-height: 15pt; opacity: 1.00;">4.  Compensation and Term</div>
<div class="paragraph Text_body_indent" style="line-height: 13pt; color: #000000; line-height: 13pt; opacity: 1.00;  text-decoration: none;"> </div>
<div class="paragraph Text_body_indent" style="line-height: 13pt; ">In consideration for the grant of the license and the use of the Software, and in exchange for delivery of these services, Client agrees to pay Pika Software for one year of service (the “Contract Payment”).</div>
<div class="paragraph Default" style="line-height: 13pt; margin-bottom: 0pt; margin-top: 0pt; color: #000000; font-size: 11pt; line-height: 13pt; opacity: 1.00;  text-decoration: none;"> </div>
<div class="paragraph Default" style="line-height: 13pt; margin-bottom: 0pt; margin-top: 0pt; color: #000000; font-size: 11pt; line-height: 13pt; opacity: 1.00;">The agreed upon compensation shall be paid by client to Pika Software in one installment, commencing with the execution of the agreement.</div>
<div class="paragraph Default" style="line-height: 13pt; margin-bottom: 0pt; margin-top: 0pt; color: #000000; font-size: 11pt; line-height: 13pt; opacity: 1.00;  text-decoration: none;"> </div>
<div class="paragraph Default" style="line-height: 15pt; color: #000000; font-size: 11pt; line-height: 13pt; opacity: 1.00;">This agreement shall commence on the Contract Date, and shall remain in effect for one year.</div>
<div class="paragraph WW_Body_Text_Indent_2" style="line-height: 13pt; margin-bottom: 0pt; margin-left: 0pt; margin-right: 0pt; margin-top: 0pt; text-indent: 0pt; color: #000000; line-height: 13pt; opacity: 1.00;  text-decoration: none;"> </div>
<div class="paragraph Heading_1" style="line-height: 15pt; ">5.  Client Responsibilities</div>
<div class="paragraph Text_body_indent" style="line-height: 13pt; "><br />
Client acknowledges that Pika Software does not provide the following services through this contract: operation and maintenance of computer hardware, Internet access, software training, site customization, data entry, data cleanup, data import and conversion, management of user account security and passwords.  If these services are needed, the Client is responsible for making the necessary arrangements.</div>
<div class="paragraph Text_body_indent" style="line-height: 13pt; text-decoration: none;"> </div>
<div class="paragraph Heading_1" style="line-height: 15pt; ">6.  Termination and Extension</div>
<div class="paragraph Default" style="line-height: 15pt; margin-bottom: 0pt; margin-top: 0pt; color: #000000; font-weight: bold; line-height: 15pt; opacity: 1.00;  text-decoration: none;"> </div>
<div class="paragraph Text_body_indent" style="line-height: 13pt; color: #000000; line-height: 13pt; opacity: 1.00;">This agreement may be terminated at any time for any reason by mutual agreement of the parties, or by the Client upon thirty (30) days prior written notice to Pika Software, or by Pika Software upon thirty (30) days prior written notice to Client.  Negotiations for an extension of this agreement if mutually requested will be completed at least thirty (30) days prior to the expiration date of this Agreement.</div>
<div class="paragraph Default" style="line-height: 13pt; margin-bottom: 0pt; margin-top: 0pt; color: #000000; font-size: 11pt; line-height: 13pt; opacity: 1.00;  text-decoration: none;"> </div>
<div class="paragraph Heading_1" style="line-height: 15pt; ">7.  Indemnification of the Client</div>
<div class="paragraph Default" style="line-height: 15pt; margin-bottom: 0pt; margin-top: 0pt; color: #000000; font-weight: bold; line-height: 15pt; opacity: 1.00;  text-decoration: none;"> </div>
<div class="paragraph Default" style="line-height: 15pt; "><span style="color: #000000; font-size: 11pt; line-height: 13pt; opacity: 1.00; ">Pika Software agrees to indemnify and hold the Client and its board members, officers, and employees harmless from any liability (including reasonable attorney’s fees and costs) imposed against the Client by reason of the negligent actions or omissions of Pika Software or employees in performing services specified in this Agreement</span><span style="color: #000000; line-height: 15pt; opacity: 1.00; ">.</span></div>
<div class="paragraph Default" style="line-height: 15pt; margin-bottom: 0pt; margin-top: 0pt; color: #000000; font-weight: bold; line-height: 15pt; opacity: 1.00;  text-decoration: none;"> </div>
<div class="paragraph Heading_1" style="line-height: 15pt; ">8.  Indemnification of Pika Software</div>
<div class="paragraph Default" style="line-height: 15pt; margin-bottom: 0pt; margin-top: 0pt; color: #000000; font-weight: bold; line-height: 15pt; opacity: 1.00;  text-decoration: none;"> </div>
<div class="paragraph Text_body_indent" style="line-height: 13pt; color: #000000; line-height: 13pt; opacity: 1.00;">The Client agrees to indemnify and hold Pika Software harmless from any liability (including reasonable attorney’s fees and costs) imposed against Pika Software by reason of the negligent actions or omissions of the Client or its employees in performing its services specified in the Agreement.</div>
<div class="paragraph Text_body_indent" style="line-height: 13pt; color: #000000; line-height: 13pt; opacity: 1.00;  text-decoration: none;"> </div>
<div class="paragraph Heading_1" style="line-height: 15pt; ">9.  Choice of Law</div>
<div class="paragraph Text_body_indent" style="line-height: 13pt; margin-bottom: 0pt; margin-left: 0pt; margin-right: 0pt; margin-top: 0pt; text-indent: 0pt; color: #000000; font-weight: bold; line-height: 13pt; opacity: 1.00;  text-decoration: none;"> </div>
<div class="paragraph Text_body_indent" style="line-height: 13pt; margin-bottom: 0pt; margin-left: 0pt; margin-right: 0pt; margin-top: 0pt; text-indent: 0pt; color: #000000; font-size: 11pt; line-height: 13pt; opacity: 1.00;">This Agreement shall be executed in connection here with shall be construed and governed by the laws of the State of Ohio and shall be binding upon and inure to the benefit of the parties hereto.  The parties agree to submit to the jurisdiction of the courts within the State of Ohio.</div>
<div class="paragraph Text_body_indent" style="line-height: 13pt; color: #000000; line-height: 13pt; opacity: 1.00;  text-decoration: none;"> </div>
<div class="paragraph Heading_1" style="line-height: 15pt; ">10.  Remedies for Breach</div>
<div class="paragraph Text_body_indent" style="line-height: 13pt; margin-bottom: 0pt; margin-left: 0pt; margin-right: 0pt; margin-top: 0pt; text-indent: 0pt; color: #000000; font-weight: bold; line-height: 13pt; opacity: 1.00;  text-decoration: none;"> </div>
<div class="paragraph Text_body_indent" style="line-height: 13pt; margin-bottom: 0pt; margin-left: 0pt; margin-right: 0pt; margin-top: 0pt; text-indent: 0pt; color: #000000; font-size: 11pt; line-height: 13pt; opacity: 1.00;">If either party breaches the above agreement, the offended party shall have the right to apply to a court of competent jurisdiction for an order to enforce the terms of this section so breached. However, the right to such application shall only occur after the offended party has provided written notice, permitting the other party to cure any breach or defect, and such breach or defect is not cured within 30 days of the date such notice was delivered.</div>
<div class="paragraph Text_body_indent" style="line-height: 13pt; color: #000000; line-height: 13pt; opacity: 1.00;  text-decoration: none;"> </div>
<div class="paragraph Heading_1" style="line-height: 15pt; ">11.  Termination</div>
<div class="paragraph Text_body_indent" style="line-height: 13pt; margin-bottom: 0pt; margin-left: 0pt; margin-right: 0pt; margin-top: 0pt; text-indent: 0pt; color: #000000; font-weight: bold; line-height: 13pt; opacity: 1.00;  text-decoration: none;"> </div>
<div class="paragraph Text_body_indent" style="line-height: 13pt; margin-bottom: 0pt; margin-left: 0pt; margin-right: 0pt; margin-top: 0pt; text-indent: 0pt; "><span style="color: #000000; font-size: 11pt; line-height: 13pt; opacity: 1.00; ">If one party (offending party) breaches one or more obligations hereunder, the other party (offended party) shall give the offending party notice, which shall specify the nature of the breach.  The offending party shall then have 30 days from the receipt of such notice to remedy the breach for which such notice has been given.  If at the end of such 30 day period, the Offending party has not cured the breach, the Offended party may thereupon terminate this Agreement by giving the offending party a written notice of termination and at the expiration of the 14</span><span style="color: #000000; font-size: 7.3pt; line-height: 13pt; opacity: 1.00; vertical-align: 0.50em; ">th</span><span style="color: #000000; font-size: 11pt; line-height: 13pt; opacity: 1.00; "> day following the delivery of such notice, the agreement shall be deemed to be terminated and the offended party shall be relieved from further performance of its obligations hereunder.</span></div>
<div class="paragraph Text_body_indent" style="line-height: 13pt; margin-bottom: 0pt; margin-left: 0pt; margin-right: 0pt; margin-top: 0pt; text-indent: 0pt; color: #000000; line-height: 13pt; opacity: 1.00;  text-decoration: none;"> </div>
<div class="paragraph Heading_1" style="line-height: 15pt; ">12.  Termination by Pika Software</div>
<div class="paragraph Text_body_indent" style="line-height: 13pt; margin-bottom: 0pt; margin-left: 0pt; margin-right: 0pt; margin-top: 0pt; text-indent: 0pt; color: #000000; font-weight: bold; line-height: 13pt; opacity: 1.00;  text-decoration: none;"> </div>
<div class="paragraph Text_body_indent" style="line-height: 13pt; color: #000000; line-height: 13pt; opacity: 1.00;">Notwithstanding the previous section, Pika Software may terminate this agreement upon 30 days prior written notice if the Client fails to pay Pika Software in accordance with provisions of above agreement.</div>
<div class="paragraph Text_body_indent" style="line-height: 13pt; margin-bottom: 0pt; margin-left: 0pt; margin-right: 0pt; margin-top: 0pt; text-indent: 0pt; color: #000000; line-height: 13pt; opacity: 1.00;  text-decoration: none;"> </div>
<div class="paragraph Heading_1" style="line-height: 15pt; ">13.  Termination by Client</div>
<div class="paragraph Text_body_indent" style="line-height: 13pt; margin-bottom: 0pt; margin-left: 0pt; margin-right: 0pt; margin-top: 0pt; text-indent: 0pt; color: #000000; font-weight: bold; line-height: 13pt; opacity: 1.00;  text-decoration: none;"> </div>
<div class="paragraph Text_body_indent" style="line-height: 13pt; color: #000000; line-height: 13pt; opacity: 1.00;">Client may terminate this agreement when it determines that termination is in the best interests of the Client by giving Pika Software 30 day’s written notice of the termination.  If the agreement is terminated per this section, Pika Software shall be paid its fee for all services actually rendered to date of termination.</div>
<div class="paragraph Text_body_indent" style="line-height: 13pt; color: #000000; line-height: 13pt; opacity: 1.00;  text-decoration: none;"> </div>
<div class="paragraph Heading_1" style="line-height: 15pt; ">14.  Severability Clause</div>
<div class="paragraph Text_body_indent" style="line-height: 13pt; margin-bottom: 0pt; margin-left: 0pt; margin-right: 0pt; margin-top: 0pt; text-indent: 0pt; color: #000000; font-weight: bold; line-height: 13pt; opacity: 1.00;  text-decoration: none;"> </div>
<div class="paragraph Text_body_indent" style="line-height: 13pt; color: #000000; line-height: 13pt; opacity: 1.00;">If a court holds any part, term, or provision of the Agreement to be unenforceable, the validity of the remaining portions or provisions shall not be affected, and the rights and obligations of the parties shall be construed and enforced as if this Agreement did not contain the particular part, term or provision.  The parties agree that any agreement by the Client to indemnify shall be construed to be enforceable to the maximum extent allowed by law.</div>
<div class="paragraph Text_body_indent" style="line-height: 13pt; color: #000000; line-height: 13pt; opacity: 1.00;  text-decoration: none;"> </div>
<div class="paragraph Heading_1" style="line-height: 15pt; ">15.  Headings</div>
<div class="paragraph Text_body_indent" style="line-height: 13pt; margin-bottom: 0pt; margin-left: 0pt; margin-right: 0pt; margin-top: 0pt; text-indent: 0pt; color: #000000; font-weight: bold; line-height: 13pt; opacity: 1.00;  text-decoration: none;"> </div>
<div class="paragraph Text_body_indent" style="line-height: 13pt; color: #000000; line-height: 13pt; opacity: 1.00;">The headings that appear in this agreement have been inserted for the purpose of convenience and ready reference.  They are not intended to and shall not be deemed to define, limit or extend the scope or intent of any provision thereof.</div>
<div class="paragraph Text_body_indent" style="line-height: 13pt; color: #000000; line-height: 13pt; opacity: 1.00;  text-decoration: none;"> </div>
<div class="paragraph Heading_1" style="line-height: 15pt; ">16.  The Client’s Authority</div>
<div class="paragraph Text_body_indent" style="line-height: 13pt; margin-bottom: 0pt; margin-left: 0pt; margin-right: 0pt; margin-top: 0pt; text-indent: 0pt; color: #000000; font-weight: bold; line-height: 13pt; opacity: 1.00;  text-decoration: none;"> </div>
<div class="paragraph Text_body_indent" style="line-height: 13pt; margin-bottom: 0pt; margin-left: 0pt; margin-right: 0pt; margin-top: 0pt; text-indent: 0pt; color: #000000; font-size: 11pt; line-height: 13pt; opacity: 1.00;">The Client represents and warrants to Pika Software that the Client (by and through its representative) has the requisite power and authority to enter into and perform the terms of this agreement and that the Client has done and will continue to do all things necessary so that this agreement will be valid, binding, and legally enforceable upon the Client.</div>
<div class="paragraph Text_body_indent" style="line-height: 13pt; margin-bottom: 0pt; margin-left: 0pt; margin-right: 0pt; margin-top: 0pt; text-indent: 0pt; color: #000000; line-height: 13pt; opacity: 1.00;  text-decoration: none;"> </div>
<div class="paragraph Heading_1" style="line-height: 15pt; ">17.  Assignments</div>
<div class="paragraph Text_body_indent" style="line-height: 13pt; margin-bottom: 0pt; margin-left: 0pt; margin-right: 0pt; margin-top: 0pt; text-indent: 0pt; color: #000000; font-weight: bold; line-height: 13pt; opacity: 1.00;  text-decoration: none;"> </div>
<div class="paragraph Text_body_indent" style="line-height: 13pt; color: #000000; line-height: 13pt; opacity: 1.00;">This agreement is not assignable by either party without the prior written consent of the other party, except for an assignment by either party to a parent or a controlled subsidiary or that party.</div>
<div class="paragraph Text_body_indent" style="line-height: 13pt; color: #000000; line-height: 13pt; opacity: 1.00;  text-decoration: none;"> </div>
<div class="paragraph Heading_1" style="line-height: 15pt; ">18.  Limitation of Claims</div>
<div class="paragraph Text_body_indent" style="line-height: 13pt; margin-bottom: 0pt; margin-left: 0pt; margin-right: 0pt; margin-top: 0pt; text-indent: 0pt; color: #000000; font-weight: bold; line-height: 13pt; opacity: 1.00;  text-decoration: none;"> </div>
<div class="paragraph Text_body_indent" style="line-height: 13pt; color: #000000; line-height: 13pt; opacity: 1.00;">Claims of either party against the other not presented to the other party in writing within one year of the date the time allowed on the applicable statute of limitations, whichever is longer.</div>
<div class="paragraph Text_body_indent" style="line-height: 13pt; margin-bottom: 0pt; margin-left: 0pt; margin-right: 0pt; margin-top: 0pt; text-indent: 0pt; color: #000000; line-height: 13pt; opacity: 1.00;  text-decoration: none;"> </div>
<div class="paragraph Heading_1" style="line-height: 15pt; ">19.  Consequential Damages</div>
<div class="paragraph Text_body_indent" style="line-height: 13pt; margin-bottom: 0pt; margin-left: 0pt; margin-right: 0pt; margin-top: 0pt; text-indent: 0pt; color: #000000; font-weight: bold; line-height: 13pt; opacity: 1.00;  text-decoration: none;"> </div>
<div class="paragraph Text_body_indent" style="line-height: 13pt; margin-bottom: 0pt; margin-left: 0pt; margin-right: 0pt; margin-top: 0pt; text-indent: 0pt; color: #000000; font-size: 11pt; line-height: 13pt; opacity: 1.00;">The parties agree that in no case shall Pika Software or the Client be liable for any loss of business, consequential, compensatory, emotional or indirect damages.</div>
<div class="paragraph Text_body_indent" style="line-height: 13pt; color: #000000; line-height: 13pt; opacity: 1.00;  text-decoration: none;"> </div>
<div class="paragraph Heading_1" style="line-height: 15pt; ">20.  Entire Agreement and Notice</div>
<div class="paragraph Text_body_indent" style="line-height: 13pt; margin-bottom: 0pt; margin-left: 0pt; margin-right: 0pt; margin-top: 0pt; text-indent: 0pt; color: #000000; font-weight: bold; line-height: 13pt; opacity: 1.00;  text-decoration: none;"> </div>
<div class="paragraph Text_body_indent" style="line-height: 13pt; margin-bottom: 0pt; margin-left: 0pt; margin-right: 0pt; margin-top: 0pt; padding-bottom: 0pt; text-indent: 0pt; "><span style="color: #000000; font-size: 11pt; line-height: 13pt; opacity: 1.00; ">This Software License Agreement contains the entire understanding of the parties related to the</span><a name="OLE_LINK1" style="color: #000000; font-size: 11pt; line-height: 13pt; opacity: 1.00; " id="OLE_LINK1"> Contract Services</a><span style="color: #000000; font-size: 11pt; line-height: 13pt; opacity: 1.00; "> and may not be amended without the specific written consent of both parties.  Any notice given under this Agreement shall be sufficient if it is in writing and if sent by certified or registered mail.</span></div>
</div>
</div>
</body>
</html>
