ALTER TABLE activities ADD COLUMN created TIMESTAMP NULL DEFAULT NULL AFTER last_changed;
ALTER TABLE cases MODIFY COLUMN created TIMESTAMP NULL DEFAULT NULL;
UPDATE cases SET created = NULL WHERE created = '0000-00-00 00:00:00';